import { Might, Position } from "../../utils/apiModels"

export const AUTHORIZATION = "Authorization";
export const ENCOUNTER_ID = "ENCOUNTERID";

export const SIGNALR_CODES = {
    SUCCESS: "SUCCESS"
}

export const BOARD = Array(161 + 10).fill("");

export const BOARD_MAPPING: { [key: number]: Position } = {
    9: { xPosition: -8, yPosition: 0 },
    27: { xPosition: -8, yPosition: 1 },
    45: { xPosition: -8, yPosition: 2 },
    63: { xPosition: -8, yPosition: 3 },
    81: { xPosition: -8, yPosition: 4 },
    99: { xPosition: -8, yPosition: 5 },
    117: { xPosition: -8, yPosition: 6 },
    135: { xPosition: -8, yPosition: 7 },
    153: { xPosition: -8, yPosition: 8 },
    1: { xPosition: -7, yPosition: -1 },
    19: { xPosition: -7, yPosition: 0 },
    37: { xPosition: -7, yPosition: 1 },
    55: { xPosition: -7, yPosition: 2 },
    73: { xPosition: -7, yPosition: 3 },
    91: { xPosition: -7, yPosition: 4 },
    109: { xPosition: -7, yPosition: 5 },
    127: { xPosition: -7, yPosition: 6 },
    145: { xPosition: -7, yPosition: 7 },
    163: { xPosition: -7, yPosition: 8 },
    10: { xPosition: -6, yPosition: -1 },
    28: { xPosition: -6, yPosition: 0 },
    46: { xPosition: -6, yPosition: 1 },
    64: { xPosition: -6, yPosition: 2 },
    82: { xPosition: -6, yPosition: 3 },
    100: { xPosition: -6, yPosition: 4 },
    118: { xPosition: -6, yPosition: 5 },
    136: { xPosition: -6, yPosition: 6 },
    154: { xPosition: -6, yPosition: 7 },
    2: { xPosition: -5, yPosition: -2 },
    20: { xPosition: -5, yPosition: -1 },
    38: { xPosition: -5, yPosition: 0 },
    56: { xPosition: -5, yPosition: 1 },
    74: { xPosition: -5, yPosition: 2 },
    92: { xPosition: -5, yPosition: 3 },
    110: { xPosition: -5, yPosition: 4 },
    128: { xPosition: -5, yPosition: 5 },
    146: { xPosition: -5, yPosition: 6 },
    164: { xPosition: -5, yPosition: 7 },
    11: { xPosition: -4, yPosition: -2 },
    29: { xPosition: -4, yPosition: -1 },
    47: { xPosition: -4, yPosition: 0 },
    65: { xPosition: -4, yPosition: 1 },
    83: { xPosition: -4, yPosition: 2 },
    101: { xPosition: -4, yPosition: 3 },
    119: { xPosition: -4, yPosition: 4 },
    137: { xPosition: -4, yPosition: 5 },
    155: { xPosition: -4, yPosition: 6 },
    3: { xPosition: -3, yPosition: -3 },
    21: { xPosition: -3, yPosition: -2 },
    39: { xPosition: -3, yPosition: -1 },
    57: { xPosition: -3, yPosition: 0 },
    75: { xPosition: -3, yPosition: 1 },
    93: { xPosition: -3, yPosition: 2 },
    111: { xPosition: -3, yPosition: 3 },
    129: { xPosition: -3, yPosition: 4 },
    147: { xPosition: -3, yPosition: 5 },
    165: { xPosition: -3, yPosition: 6 },
    12: { xPosition: -2, yPosition: -3 },
    30: { xPosition: -2, yPosition: -2 },
    48: { xPosition: -2, yPosition: -1 },
    66: { xPosition: -2, yPosition: 0 },
    84: { xPosition: -2, yPosition: 1 },
    102: { xPosition: -2, yPosition: 2 },
    120: { xPosition: -2, yPosition: 3 },
    138: { xPosition: -2, yPosition: 4 },
    156: { xPosition: -2, yPosition: 5 },
    4: { xPosition: -1, yPosition: -4 },
    22: { xPosition: -1, yPosition: -3 },
    40: { xPosition: -1, yPosition: -2 },
    58: { xPosition: -1, yPosition: -1 },
    76: { xPosition: -1, yPosition: 0 },
    94: { xPosition: -1, yPosition: 1 },
    112: { xPosition: -1, yPosition: 2 },
    130: { xPosition: -1, yPosition: 3 },
    148: { xPosition: -1, yPosition: 4 },
    166: { xPosition: -1, yPosition: 5 },
    13: { xPosition: 0, yPosition: -4 },
    31: { xPosition: 0, yPosition: -3 },
    49: { xPosition: 0, yPosition: -2 },
    67: { xPosition: 0, yPosition: -1 },
    85: { xPosition: 0, yPosition: 0 },
    103: { xPosition: 0, yPosition: 1 },
    121: { xPosition: 0, yPosition: 2 },
    139: { xPosition: 0, yPosition: 3 },
    157: { xPosition: 0, yPosition: 4 },
    5: { xPosition: 1, yPosition: -5 },
    23: { xPosition: 1, yPosition: -4 },
    41: { xPosition: 1, yPosition: -3 },
    59: { xPosition: 1, yPosition: -2 },
    77: { xPosition: 1, yPosition: -1 },
    95: { xPosition: 1, yPosition: 0 },
    113: { xPosition: 1, yPosition: 1 },
    131: { xPosition: 1, yPosition: 2 },
    149: { xPosition: 1, yPosition: 3 },
    167: { xPosition: 1, yPosition: 4 },
    14: { xPosition: 2, yPosition: -5 },
    32: { xPosition: 2, yPosition: -4 },
    50: { xPosition: 2, yPosition: -3 },
    68: { xPosition: 2, yPosition: -2 },
    86: { xPosition: 2, yPosition: -1 },
    104: { xPosition: 2, yPosition: 0 },
    122: { xPosition: 2, yPosition: 1 },
    140: { xPosition: 2, yPosition: 2 },
    158: { xPosition: 2, yPosition: 3 },
    6: { xPosition: 3, yPosition: -6 },
    24: { xPosition: 3, yPosition: -5 },
    42: { xPosition: 3, yPosition: -4 },
    60: { xPosition: 3, yPosition: -3 },
    78: { xPosition: 3, yPosition: -2 },
    96: { xPosition: 3, yPosition: -1 },
    114: { xPosition: 3, yPosition: 0 },
    132: { xPosition: 3, yPosition: 1 },
    150: { xPosition: 3, yPosition: 2 },
    168: { xPosition: 3, yPosition: 3 },
    15: { xPosition: 4, yPosition: -6 },
    33: { xPosition: 4, yPosition: -5 },
    51: { xPosition: 4, yPosition: -4 },
    69: { xPosition: 4, yPosition: -3 },
    87: { xPosition: 4, yPosition: -2 },
    105: { xPosition: 4, yPosition: -1 },
    123: { xPosition: 4, yPosition: 0 },
    141: { xPosition: 4, yPosition: 1 },
    159: { xPosition: 4, yPosition: 2 },
    7: { xPosition: 5, yPosition: -7 },
    25: { xPosition: 5, yPosition: -6 },
    43: { xPosition: 5, yPosition: -5 },
    61: { xPosition: 5, yPosition: -4 },
    79: { xPosition: 5, yPosition: -3 },
    97: { xPosition: 5, yPosition: -2 },
    115: { xPosition: 5, yPosition: -1 },
    133: { xPosition: 5, yPosition: 0 },
    151: { xPosition: 5, yPosition: 1 },
    169: { xPosition: 5, yPosition: 2 },
    16: { xPosition: 6, yPosition: -7 },
    34: { xPosition: 6, yPosition: -6 },
    52: { xPosition: 6, yPosition: -5 },
    70: { xPosition: 6, yPosition: -4 },
    88: { xPosition: 6, yPosition: -3 },
    106: { xPosition: 6, yPosition: -2 },
    124: { xPosition: 6, yPosition: -1 },
    142: { xPosition: 6, yPosition: 0 },
    160: { xPosition: 6, yPosition: 1 },
    8: { xPosition: 7, yPosition: -8 },
    26: { xPosition: 7, yPosition: -7 },
    44: { xPosition: 7, yPosition: -6 },
    62: { xPosition: 7, yPosition: -5 },
    80: { xPosition: 7, yPosition: -4 },
    98: { xPosition: 7, yPosition: -3 },
    116: { xPosition: 7, yPosition: -2 },
    134: { xPosition: 7, yPosition: -1 },
    152: { xPosition: 7, yPosition: 0 },
    170: { xPosition: 7, yPosition: 1 },
    17: { xPosition: 8, yPosition: -8 },
    35: { xPosition: 8, yPosition: -7 },
    53: { xPosition: 8, yPosition: -6 },
    71: { xPosition: 8, yPosition: -5 },
    89: { xPosition: 8, yPosition: -4 },
    107: { xPosition: 8, yPosition: -3 },
    125: { xPosition: 8, yPosition: -2 },
    143: { xPosition: 8, yPosition: -1 },
    161: { xPosition: 8, yPosition: 0 }
}

export const COLORS = {
    [Might.White]: "bg-gray-100 text-gray-900",
    [Might.Yellow]: "bg-yellow-400 text-gray-900",
    [Might.Red]: "bg-red-600 text-gray-900",
    [Might.Black]: "bg-gray-900 text-gray-100"
}

export const HIGHLIGHTS = {
    [Might.White]: "hover:shadow-gray-50",
    [Might.Yellow]: "hover:shadow-yellow-200",
    [Might.Red]: "hover:shadow-red-400",
    [Might.Black]: "hover:shadow-gray-800"
}


export const formatBossPart = (bossPart: string) => {
    const bossPartSplit = bossPart.split(" ");
    return bossPartSplit[1] === "0" ? bossPartSplit[0] : bossPart; 
}
